# Spatial Land Development and Valuation Estimations {#Speculation-Across-The-Nation}

#### Keywords {-}

Land Speculation, Spatial Analytics, Development

## Land Development and Gentrification

Urbanization, gentrification and development. According to the World Bank, the march of humanity reclaiming untamed lands has progressed at a steady rate [Citation Here]. Where rural lands 20 years agos, once bucolic oasis, are now densely populated urban hot spots with schools, access to amenities and local transportation. For Developers, homeowners and speculators, the future value of property remains at arms reach but has a massive impact on their ability to remain in business or save for retirement. 

This solution seeks to create an AI based Deep Learning Model to evaluate statistics on immigration trends, land development historical access to amenities. In combination with using spatial analytics via historic satellite imagery,  business data, Census data, and public record land values. We are seeking to create an AI to calculate future expected land valuations specific tested time periods, the value added is to more accurately access land valuations. 

## Study Goals & Project Plan

Outside the scope of this plan are to study other potential factor such as economic incentive plans,  tax incentives, state development plans, due to the highly subjective and opaque deals. 

Biases:
Potential pitfalls to lookout for Selection bias, Availability bias.

Supervised Machine learning models will be fed with 40 years of historic US based land development data records, with the key goal of this data is to create AI that will forecast future urbanization based off past development and design an estimation price model for land with similar characteristics. 

Data to be used:
Zillow
Census Data
Dunn and Bradd Street Data
Historic Traffic Records
Public Record Land valuation.

```{r experimental,echo=F,results='asis',eval=F}
data.table::fread('https://raw.githubusercontent.com/UCB-MIDS/experiments-causality/master/data/GerberGreenBook_Chapter3_Donations.csv?token=ABNmuX-Q14rzQ4teItDenc9L5Wo2flncks5ZL5qEwA%3D%3D') %>% stargazer::stargazer(type = 'html',title = 'Something from W241 Experiments and Causality')
```

## Future Plans for the Study

What we are hoping to do is create a highly accurate statistical model that will enable us to look into future speculation In new.This is still be executed only United States. 

